### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by creativeosmose** [biker91620/ha-cozytouch#16]
Hi,

I'm having issues installing your component.
I'm running Hass.io version 193 / 0.103.6.
I have Malicio 2 water heaters working with Cozytouch.

I've tried installing your component in custom components and in regular components, none have worked. The regular one was indicated in one of this git's previous issues.

The custom one returns errors for each approach (switch, climate, etc).
I never manage to obtain the component.

Here is the error:

_Error while setting up platform cozytouch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/cozytouch/switch.py", line 35, in setup_platform
    from cozypy.constant import DeviceType
ModuleNotFoundError: No module named 'cozypy'_

Thanks for your help,

**Comment by creativeosmose** [comment]
Fixed using the HACS approach.
