### ISSUE TITLE
Periodic Errorr on port 443

### ISSUE THREAD

**Issue by jugla** [biker91620/ha-cozytouch#22]
I have CozyTouch : 1.4.1b (within hacs).
In log , I've got periodic error on port 443
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ha110-1.overkiz.com', port=443): Max retries exceeded with url: /enduser-mobile-web/enduserAPI/setup/devices/io%3A%2F2F0825-3323-9670%2F8076481%235/states (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xa40df4f0>, 'Connection to ha110-1.overkiz.com timed out. (conect timeout=30)'))
`

**Comment by cyr-ius** [comment]
Update your version, this has been fixed.

**Comment by jugla** [comment]
Yes I confirm. The issue can be closed.
Thanks again!
